name: battery
description: To check the flow of waste batteries with blockchain.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.3.0
  dotted_border: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  page_view_indicator: ^0.3.0+1
  dots_indicator: ^0.0.5+1
  shared_preferences: ^0.5.3+4
  dio: ^2.1.13
  http: ^0.12.0+2
  rxdart: ^0.22.1+1
  provider: ^3.0.0+1
  charts_flutter: ^0.8.1
  flutter_datetime_picker: ^1.2.8

  #ethereum
  meta: ^1.1.6
  convert: ^2.1.1
  quiver: '>=2.0.0 <3.0.0'
  pointycastle: ^1.0.1
  equatable: ^0.2.3
  collection: ^1.14.11
  json_schema: ^2.2.0
  json_annotation: ^3.0.0
  buffer: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #ethereum
  build_runner: ^1.3.0
  json_serializable: ^3.0.0
  path: ^1.6.2
  test: ^1.6.2
    


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts: 
    - family: Nanum Gothic
      fonts: 
        - asset: fonts/NanumGothic_Regular.ttf
    - family: Nanum Gothic bold
      fonts:
        - asset: fonts/NanumGothic_bold.ttf
    - family: Spoqa Han San
      fonts:
        - asset: fonts/SpoqaHanSans_Regular.ttf
    - family: Montserrat Semi Bold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: AppleSD Gothic Semi Bold
      fonts:
        - asset: fonts/AppleSDGothicNeoSB.ttf
    - family: AppleSD Gothic Light
      fonts:
        - asset: fonts/AppleSDGothicNeoL.ttf
        
  assets:
    - images/logo.png
    - images/kakao.png
    - images/naver.png
    - images/mail.png
    - images/combined_shape.png
    - images/document.png
    - images/edit_2.png
    - images/notifications_bell_button.png
    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # To add assets to your application, add an assets section, like this:  
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
